name: cleanup preview

on:
  pull_request:
    types: [closed]

permissions:
  id-token: write
  contents: read

jobs:
  cleanup:
    name: cleanup preview
    runs-on: shopware-arm64
    container: ghcr.io/catthehacker/ubuntu:act-22.04

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          role-session-name: ${{ secrets.AWS_ROLE_SESSION_NAME }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: cleanup preview
        run: |
          npm ci && npx sst remove --stage ${{ github.event.number }}
